import type { Metadata } from "next";

import "./globals.css";

import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#F7FBFF] flex h-screen">
        <Sidebar />
        <main className="p-10 max-w-7xl mx-auto">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
